name: Downloading and uploading FDA 510k Device Summaries

on:
  # Only run when the medical-device-predicate-graph project changes
  push:
    paths:
      - "medical-device-predicate-graph/**"

  # Run at 1:11 AM UTC on Sat / 8:11 PM EST on Fri
  schedule:
    - cron: "11 1 * * 6"
  workflow_dispatch:
    inputs:
      since_date:
        description: "The date to check from for newly posted devices"
        required: true
        default: "2022-01-01"
        type: string
jobs:
  build:
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Install linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y poppler-utils ocrmypdf pcregrep
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"
      - name: Download new fda device summary documents
        run: |
          cd medical-device-predicate-graph
          export MONTH_AGO=$(date -d "-1 month" +%Y-%m-%d)
          if [ -z "$SINCE_DATE" ]; then export SINCE_DATE="$MONTH_AGO"; fi
          python3 download_device_documents.py --since="$SINCE_DATE" --dst-folder=raw --dry-run=False
        env:
          SINCE_DATE: ${{ github.event.inputs.since_date }}
      - name: Convert new fda device summary documents to text
        run: |
          cd medical-device-predicate-graph
          python3 convert_pdf_to_text.py --src-dir=raw --dst-dir=text --dry-run=False
      - name: Upload device summary PDFs to Google Cloud storage
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "medical-device-predicate-graph/raw"
          destination: "fda_devices/raw"
          parent: "false"
      - name: Upload device summary text files to Google Cloud storage
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: "medical-device-predicate-graph/text"
          destination: "fda_devices/text"
          parent: "false"
      - name: Download all device text files, generate graph and persist graph to Google Cloud Storage.
        run: |
          cd medical-device-predicate-graph
          gsutil -m cp --recursive 'gs://fda_devices/text/*' text
          ./extract_predicates.sh text
          python3 analyze_graph.py
          gsutil -m cp  graph.json 'gs://fda_devices/graph.json'
