# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 17 * * *'
  workflow_dispatch:
    inputs:
      since_date:
        description: 'The date to check from for newly posted devices'
        required: true
        default: '2022-01-01'
        type: string
jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'
    - name: Download new fda device documents
      run: |
        cd medical-device-predicate-graph
        export SINCE_DATE=${SINCE_DATE:-'2022-01-01'}
        python3 download_device_documents.py --since="$SINCE_DATE" --dst-folder=raw --dry-run=False
      env:
        SINCE_DATE: ${{ github.event.inputs.since_date }}
    - uses: 'google-github-actions/upload-cloud-storage@v0'
      with:
        path: 'medical-device-predicate-graph/raw'
        destination: 'fda_devices/raw'
        parent: 'false'
